spring.datasource.url=jdbc:h2:mem:fixnow
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=false

server.error.whitelabel.enabled=false
spring.web.resources.add-mappings=true
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

logging.level.org.springframework.security=DEBUG